Server:
  RunMode: release
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
  ContextTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
#  上传文件的最终保存目录。
  UploadSavePath: storage/uploads
#    上传文件后的用于展示的文件服务地址。
  UploadServerUrl: http://127.0.0.1:8000/static
#    上传文件所允许的最大空间大小（MB）
  UploadImageMaxSize: 5  # MB
#    上传文件所允许的文件后缀。
  UploadImageAllowExts:
      - .jpg
      - .jpeg
      - .png
DataBase:
  DBType: mysql
  UserName: root
  Password: 123456
  Host: 43.142.46.98:3306
  DBName: newApp
  TablePrefix: app
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: eddycjy
  Issuer: app-service
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 1479425620@qq.com
  Password: eoxfolpimwyvffji
  IsSSL: true
  From: 1479425620@qq.com
  To:
    - 610900762@qq.com